set(REDLINE_ROOT $ENV{HOME}/.local/redline)
set(ROLE_NAME ${CMAKE_PROJECT_NAME})
set(ROLE_DIR ${REDLINE_ROOT}/${ROLE_NAME})
set(ROLE_CACHE_DIR ${ROLE_DIR}/cache)

# Setup role-specific paths
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${ROLE_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${ROLE_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${ROLE_DIR}/lib)
